version : '3'
services:
  express-api:
    image: tudor43171/express-api:v9
    ports: 
      - 3000:3000
  react:
    image: tudor43171/react-frontend:v7 
    ports:
      - 80:5173
  db:
    image: tudor43171/postgres-db:v2          
